Repository calvin0327/cloudtty, pull requests merged in 2024-05, with the labels that each got.

#156 test robot
  .github/workflows/build-helm-release.yaml
Labels: size/XS, lgtm, dco-signoff: yes, approved

#157 test robot
  Makefile
Labels: size/XS, lgtm, dco-signoff: yes, approved

#159 test robot4
  .github/workflows/call-lint-chart.yaml
  .github/workflows/test-pr.yaml
  OWNERS
Labels: kind/bug, kind/cleanup, lgtm, dco-signoff: yes, approved, size/L

#161 test robot6
  OWNERS
Labels: kind/cleanup, size/XS, lgtm, dco-signoff: yes, approved

#163 Test robot8
  .github/workflows/bot.yaml
  .github/workflows/call-lint-chart.yaml
  .github/workflows/test-pr.yaml
Labels: kind/bug, kind/cleanup, lgtm, dco-signoff: yes, approved, size/L

#164 test robot9
  CODE_OF_CONDUCT.md
Labels: kind/bug, size/XS, lgtm, dco-signoff: yes, approved

#165 test robot10
  MAINTAINERS.md
Labels: size/XS, lgtm, dco-signoff: yes, approved
